#!/usr/bin/env python3
"""Assemble index.html from the components in src/.

Each poster is one self-contained file in src/posters/ carrying its own styles,
markup and — where it renders live data — its own init script. This script
inlines them into src/page.html, stacked into the dependency tiers that
src/graph.json implies.

The output is committed: GitHub Pages serves it directly, so the page stays
crawlable and needs no JavaScript to render its structure. There is no
dependency beyond the standard library.

Why not Jekyll, which Pages would run for free: the http-files.org poster
prints `{{host}}` as part of a real .http specimen, and Liquid would consume
it. `.nojekyll` stays, and the placeholders here are HTML comments for the
same reason.

    python3 build.py            # write index.html
    python3 build.py --check    # exit 1 if index.html is stale
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'index.html')


def read(*parts):
    with open(os.path.join(*parts), encoding='utf-8') as fh:
        return fh.read()


def split_component(text):
    """Pull the <style>, <script> and markup apart. Both blocks are optional."""
    style = ''
    script = ''

    def take_style(m):
        nonlocal style
        style += m.group(1)
        return ''

    def take_script(m):
        nonlocal script
        script += m.group(1)
        return ''

    body = re.sub(r'<style>\n?(.*?)</style>\n?', take_style, text, flags=re.S)
    body = re.sub(r'<script>\n?(.*?)</script>\n?', take_script, body, flags=re.S)
    body = re.sub(r'^<!--[^\n]*-->\n', '', body)          # drop the title comment
    return style.strip('\n'), script.strip('\n'), body.strip('\n')


def indent(text, spaces):
    pad = ' ' * spaces
    return '\n'.join(pad + ln if ln.strip() else ln for ln in text.split('\n'))


def tiers(nodes, edges):
    """Tier = the longest dependency chain starting at a node, so every poster
    sits above everything it depends on. Raises on a cycle."""
    deps = {n: [] for n in nodes}
    for e in edges:
        for end in (e['from'], e['to']):
            if end not in deps:
                raise SystemExit(f'build: graph edge names unknown poster {end!r}')
        deps[e['from']].append(e['to'])

    memo = {}

    def depth(n, seen=()):
        if n in memo:
            return memo[n]
        if n in seen:
            raise SystemExit(f'build: dependency cycle through {n!r}')
        memo[n] = 0 if not deps[n] else 1 + max(depth(d, seen + (n,)) for d in deps[n])
        return memo[n]

    for n in nodes:
        depth(n)
    return memo


def build():
    nodes = json.loads(read(SRC, 'posters.json'))
    graph = json.loads(read(SRC, 'graph.json'))
    depth = tiers(nodes, graph['edges'])
    order = graph.get('order', [])

    def rank(n):
        return order.index(n) if n in order else len(order)

    styles, scripts, blocks = [], [], []
    for tier in sorted(set(depth.values()), reverse=True):
        row = sorted([n for n in nodes if depth[n] == tier], key=rank)
        blocks.append(f'      <div class="layer" data-tier="{tier}">\n')
        for name in row:
            path = os.path.join(SRC, 'posters', name + '.html')
            if not os.path.exists(path):
                raise SystemExit(f'build: graph references missing poster {name!r}')
            style, script, markup = split_component(read(path))
            if style:
                styles.append(style)
            if script:
                scripts.append(script)
            # tag the root element so the edge renderer can find it. Anchored to
            # the start of the component rather than to a class attribute, so a
            # poster may carry any attributes in any order.
            markup, n = re.subn(r'^(\s*)<(a|div)\b',
                                rf'\1<\2 data-node="{name}"', markup, count=1)
            if n != 1:
                raise SystemExit(f'build: {name!r} has no recognisable poster root element')
            blocks.append(markup + '\n\n')
        blocks.append('      </div>\n\n')

    page = read(SRC, 'page.html')
    page = page.replace('<!--{ base.css }-->', read(SRC, 'base.css').rstrip())
    page = page.replace('<!--{ poster styles }-->', '\n'.join(styles))
    page = page.replace('<!--{ sections }-->', ''.join(blocks))
    page = page.replace('<!--{ graph }-->', json.dumps(
        {'edges': graph['edges']}, separators=(',', ':')))
    page = page.replace('<!--{ poster scripts }-->', indent('\n\n'.join(scripts), 0) + '\n')

    banner = (f'<!-- Generated by build.py from src/ — {len(nodes)} posters in '
              f'{len(set(depth.values()))} dependency tiers. Edit src/, not this file. -->\n')
    return page.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n' + banner, 1)


if __name__ == '__main__':
    html = build()
    if '--check' in sys.argv:
        current = read(OUT) if os.path.exists(OUT) else ''
        if current != html:
            print('index.html is stale — run: python3 build.py')
            sys.exit(1)
        print('index.html is up to date')
    else:
        with open(OUT, 'w', encoding='utf-8') as fh:
            fh.write(html)
        n = len(json.loads(read(SRC, 'posters.json')))
        print(f'index.html — {n} posters, {len(html):,} bytes')
