#!/usr/bin/env python3
"""Assemble index.html from the components in src/.

Each poster is one self-contained file in src/posters/ carrying its own styles,
markup and — where it renders live data — its own init script. This script
inlines them into src/page.html in the order src/sections.json declares.

The output is committed: GitHub Pages serves it directly, so the page stays
crawlable and needs no JavaScript to render its structure. There is no
dependency beyond the standard library.

Why not Jekyll, which Pages would run for free: the http-files.org poster
prints `{{host}}` as part of a real .http specimen, and Liquid would consume
it. `.nojekyll` stays, and the placeholders here are HTML comments for the
same reason.

    python3 build.py            # write index.html
    python3 build.py --check    # exit 1 if index.html is stale
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, 'src')
OUT = os.path.join(ROOT, 'index.html')


def read(*parts):
    with open(os.path.join(*parts), encoding='utf-8') as fh:
        return fh.read()


def split_component(text):
    """Pull the <style>, <script> and markup apart. Both blocks are optional."""
    style = ''
    script = ''

    def take_style(m):
        nonlocal style
        style += m.group(1)
        return ''

    def take_script(m):
        nonlocal script
        script += m.group(1)
        return ''

    body = re.sub(r'<style>\n?(.*?)</style>\n?', take_style, text, flags=re.S)
    body = re.sub(r'<script>\n?(.*?)</script>\n?', take_script, body, flags=re.S)
    body = re.sub(r'^<!--[^\n]*-->\n', '', body)          # drop the title comment
    return style.strip('\n'), script.strip('\n'), body.strip('\n')


def indent(text, spaces):
    pad = ' ' * spaces
    return '\n'.join(pad + ln if ln.strip() else ln for ln in text.split('\n'))


def build():
    sections = json.loads(read(SRC, 'sections.json'))

    styles, scripts, blocks = [], [], []
    for section in sections:
        posters = section['posters']
        blocks.append(
            '      <section class="domain">\n'
            '        <header class="domain-head">\n'
            f'          <h2>{section["title"]}</h2>\n'
            f'          <span class="domain-sub">{section["sub"]}</span>\n'
            '          <span class="domain-rule" aria-hidden="true"></span>\n'
            f'          <span class="domain-n">{len(posters):02d}</span>\n'
            '        </header>\n'
            '        <div class="wall">\n'
        )
        for name in posters:
            path = os.path.join(SRC, 'posters', name + '.html')
            if not os.path.exists(path):
                raise SystemExit(f'build: {section["title"]} references missing poster {name!r}')
            style, script, markup = split_component(read(path))
            if style:
                styles.append(style)
            if script:
                scripts.append(script)
            blocks.append(markup + '\n\n')
        blocks.append('        </div>\n      </section>\n\n')

    page = read(SRC, 'page.html')
    page = page.replace('<!--{ base.css }-->', read(SRC, 'base.css').rstrip())
    page = page.replace('<!--{ poster styles }-->', '\n'.join(styles))
    page = page.replace('<!--{ sections }-->', ''.join(blocks))
    page = page.replace('<!--{ poster scripts }-->', indent('\n\n'.join(scripts), 0) + '\n')

    count = sum(len(s['posters']) for s in sections)
    banner = (f'<!-- Generated by build.py from src/ — {count} posters in '
              f'{len(sections)} sections. Edit src/, not this file. -->\n')
    return page.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n' + banner, 1)


if __name__ == '__main__':
    html = build()
    if '--check' in sys.argv:
        current = read(OUT) if os.path.exists(OUT) else ''
        if current != html:
            print('index.html is stale — run: python3 build.py')
            sys.exit(1)
        print('index.html is up to date')
    else:
        with open(OUT, 'w', encoding='utf-8') as fh:
            fh.write(html)
        n = sum(len(s['posters']) for s in json.loads(read(SRC, 'sections.json')))
        print(f'index.html — {n} posters, {len(html):,} bytes')
